baseurl = "https://enenumxela.github.io/blog/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
    # dir name of your blog content (default is `content/posts`)
    contentTypeName = "post"

    # ["orange", "blue", "red", "green", "pink"]
    themeColor = "blue"

    # if you set this to 0, only submenu trigger will be visible
    showMenuItems = 3

    # show selector to switch language
    showLanguageSelector = false

    # set theme to full screen width
    fullWidthTheme = false

    # center theme with default width
    centerTheme = true

    # set a custom favicon (default is a `themeColor` square)
    # favicon = "favicon.ico"

    # set post to show the last updated
    # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
    showLastUpdated = false
    # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
    # updatedDatePrefix = "Updated"

    # set all headings to their default size (depending on browser settings)
    # it's set to `true` by default
    # oneHeadingSize = false

[languages]
    [languages.en]
        languageName = "English"
        title = "Alex Munene (@enenumxela) | Blog"
        subtitle = "A simple, retro theme for Hugo"
        owner = ""
        keywords = ""
        copyright = "@ Alex Munene"
        menuMore = "Show more"
        readMore = "Read more"
        readOtherPosts = "Read other posts"
        newerPosts = "Newer posts"
        olderPosts = "Older posts"
        missingContentMessage = "Page not found..."
        missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
        logoText = "enenumxela@signed"
        logoHomeLink = "https://enenumxela.github.io/blog/"

    [languages.en.menu]
        [[languages.en.menu.main]]
            identifier = "posts"
            name = "Posts"
            url = "/post"
        [[languages.en.menu.main]]
            identifier = "tags"
            name = "Tags"
            url = "/tags"
        #[[languages.en.menu.main]]
            #identifier = "about"
            #name = "About Me"
            #url = "/about"
        #[[languages.en.menu.main]]
            #identifier = "showcase"
            #name = "Showcase"
            #url = "/showcase"
